### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by rajibahmed** [casonadams/alacritty-shell#1]
Better to separate k9s config and alacritty theme generation ?

**Comment by casonadams** [comment]
What do you suggest.  I'm open to the idea!

**Comment by rajibahmed** [comment]
maybe creating two shell scripts to import separate functions

**Comment by casonadams** [comment]
maybe the bigger question is "does the k9s theme really have anything to do with alacritty theme".  Maybe it doesn't make any sense and should just be removed.  However, there is still a dependency on `yq` being installed.

**Comment by casonadams** [comment]
@rajibahmed I like the idea here.  Not every that uses this will want to have it tied to a k9s skin file.  This has been completed.
