### ISSUE TITLE
failing to initialize 

### ISSUE THREAD

**Issue by rajibahmed** [casonadams/alacritty-shell#2]
Getting this error message on OSX.

```
.config/alacritty-shell/profile_helper.sh: line 70: /yq: No such file or directory
```

https://github.com/casonadams/alacritty-shell/blob/3d6bffdf410812fe1df9b6bf16b53ce686434821/profile_helper.sh#L61

I guess you can add `yq` as deps for it on README. And not sure the loop actually work.

**Comment by casonadams** [comment]
I think I was to talk about this one a bit more.  Maybe it makes sense to require the user to install `yq` before they can use this utility?

**Comment by casonadams** [comment]
@rajibahmed I have corrected this, alacritty-shell will now look for an installed `yq` first before trying to install one.
